"""create reorder

Revision ID: 561ec463b68c
Revises: 5336fa5856ff
Create Date: 2022-11-03 07:25:48.673372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561ec463b68c'
down_revision = '5336fa5856ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('re_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('re_order')
    # ### end Alembic commands ###
